name: AI Monitoring Check

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build & run containers
        run: |
          docker-compose up -d
          sleep 10
          curl -X POST http://localhost:5000/predict -H "Content-Type: application/json" -d '{"text": "hi"}'

      - name: Run agent log check
        run: |
          docker cp $(docker ps -qf "name=ai-model"):/app/inference.log .
          python3 agent.py

      - name: Upload alert report
        uses: actions/upload-artifact@v3
        with:
          name: ai-alert-report
          path: alert.txt
