name: AI Monitoring Check

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install prometheus_client flask

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build & run Docker containers
        run: |
          docker-compose up -d
          sleep 10
          curl -X POST http://localhost:5000/predict -H "Content-Type: application/json" -d '{"text": "hi"}'

      - name: Copy inference.log from container
        run: |
          docker ps -a
          container_id=$(docker ps -qf "name=ai-model")
          docker cp $container_id:/app/inference.log .
          ls -lah

      - name: Run agent log analyzer
        run: |
          python agent.py

      - name: Upload alert report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ai-alert-report
          path: alert.txt
