name: AI Monitoring Check

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code from the repository
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask prometheus_client

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and run containers
        run: |
          docker-compose up -d
          sleep 10
          curl -X POST http://localhost:5000/predict -H "Content-Type: application/json" -d '{"text": "hi"}'

      - name: Copy inference.log from container
        run: |
          container_id=$(docker ps -qf "name=ai-model")
          docker cp $container_id:/app/inference.log .
          ls -lah

      - name: Run agent log analyzer
        run: |
          python agent.py

      - name: Upload alert report
        uses: actions/upload-artifact@v4
        with:
          name: ai-alert-report
          path: alert.txt